#!/home/ew/bin/ruby
# putting unicorn in the shebang won't work because unicorn itself is
# a ruby script, so the following is the next best thing:
exec('unicorn', $0) if $0 == __FILE__

# the below script is a standalone Sinatra application; absolutely
# nothing special needs to be done in this Sinatra app for running
# with Unicorn
require 'sinatra_example'

# the following hash needs to be the last statement, as unicorn
# will eval this entire file
{ :app => Sinatra::Application }
